import type { Pool, PoolClient } from "pg";
import type { SessionIdentity } from "../auth/repository.js";
import { withTenantTransaction } from "../database/client.js";
export type TaxRegime = "direct" | "objective" | "not_applicable";
export interface TaxProfile { incomeTaxRegime: TaxRegime; irpfRate: string; annualMinoration: string; }
const quarterBounds = (year: number, quarter: number) => ({ from: `${year}-${String((quarter - 1) * 3 + 1).padStart(2, "0")}-01`, to: new Date(Date.UTC(year, quarter * 3, 0)).toISOString().slice(0, 10) });
const n = (value: unknown) => Number(value ?? 0);
const profileQuery = `select income_tax_regime "incomeTaxRegime",irpf_rate::text "irpfRate",annual_minoration::text "annualMinoration" from tax_profiles where company_id=$1`;
export class TaxService {
  constructor(private readonly pool: Pool) {}
  async profile(i: SessionIdentity): Promise<TaxProfile> { return withTenantTransaction(this.pool,i,async c => (await c.query(profileQuery,[i.companyId])).rows[0] ?? { incomeTaxRegime:"direct",irpfRate:"20.00",annualMinoration:"0.0000" }); }
  async saveProfile(i: SessionIdentity, input: TaxProfile) { return withTenantTransaction(this.pool,i,async c => (await c.query(`insert into tax_profiles(company_id,income_tax_regime,irpf_rate,annual_minoration,updated_by_user_id) values($1,$2,$3,$4,$5) on conflict(company_id) do update set income_tax_regime=excluded.income_tax_regime,irpf_rate=excluded.irpf_rate,annual_minoration=excluded.annual_minoration,updated_by_user_id=excluded.updated_by_user_id returning income_tax_regime "incomeTaxRegime",irpf_rate::text "irpfRate",annual_minoration::text "annualMinoration"`,[i.companyId,input.incomeTaxRegime,input.irpfRate,input.annualMinoration,i.userId])).rows[0]); }
  async settlements(i: SessionIdentity) { return withTenantTransaction(this.pool,i,async c => (await c.query(`select id,tax_model "taxModel",year,quarter,estimated_amount::text "estimatedAmount",filed_amount::text "filedAmount",filed_at "filedAt",status,notes from tax_settlements where company_id=$1 order by year desc,quarter desc,tax_model`,[i.companyId])).rows); }
  async saveSettlement(i: SessionIdentity,input:{taxModel:"303"|"130";year:number;quarter:number;estimatedAmount:string;filedAmount?:string|null;filedAt?:string|null;status?:string;notes?:string|null}) { return withTenantTransaction(this.pool,i,async c => (await c.query(`insert into tax_settlements(company_id,tax_model,year,quarter,estimated_amount,filed_amount,filed_at,status,notes,created_by_user_id) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) on conflict(company_id,tax_model,year,quarter) do update set estimated_amount=excluded.estimated_amount,filed_amount=excluded.filed_amount,filed_at=excluded.filed_at,status=excluded.status,notes=excluded.notes returning id,tax_model "taxModel",year,quarter,estimated_amount::text "estimatedAmount",filed_amount::text "filedAmount",filed_at "filedAt",status,notes`,[i.companyId,input.taxModel,input.year,input.quarter,input.estimatedAmount,input.filedAmount??null,input.filedAt??null,input.status??"estimated",input.notes??null,i.userId])).rows[0]); }
  async forecast(i: SessionIdentity,year:number,quarter:number) { return withTenantTransaction(this.pool,i,async c => this.forecastWithClient(c,i,year,quarter)); }
  private async forecastWithClient(c:PoolClient,i:SessionIdentity,year:number,quarter:number) {
    const bounds=quarterBounds(year,quarter),yearStart=`${year}-01-01`,profile=(await c.query(profileQuery,[i.companyId])).rows[0] as TaxProfile ?? {incomeTaxRegime:"direct",irpfRate:"20",annualMinoration:"0"};
    const [sales,purchases,accSales,accPurchases,previous]=await Promise.all([
      c.query(`select coalesce(sum(l.line_subtotal),0) base,coalesce(sum(l.line_tax),0) tax,count(distinct inv.id) count from invoices inv join invoice_lines l on l.invoice_id=inv.id where inv.company_id=$1 and inv.direction='sale' and inv.status='issued' and inv.issue_date between $2 and $3`,[i.companyId,bounds.from,bounds.to]),
      c.query(`select coalesce(sum(l.line_subtotal),0) base,coalesce(sum(l.line_tax),0) tax,count(distinct p.id) count from purchase_invoices p join purchase_invoice_lines l on l.purchase_invoice_id=p.id and l.company_id=p.company_id where p.company_id=$1 and p.status='confirmed' and p.issue_date between $2 and $3`,[i.companyId,bounds.from,bounds.to]),
      c.query(`select coalesce(sum(l.line_subtotal),0) value from invoices inv join invoice_lines l on l.invoice_id=inv.id where inv.company_id=$1 and inv.direction='sale' and inv.status='issued' and inv.issue_date between $2 and $3`,[i.companyId,yearStart,bounds.to]),
      c.query(`select coalesce(sum(l.line_subtotal),0) value from purchase_invoices p join purchase_invoice_lines l on l.purchase_invoice_id=p.id and l.company_id=p.company_id where p.company_id=$1 and p.status='confirmed' and p.issue_date between $2 and $3`,[i.companyId,yearStart,bounds.to]),
      c.query(`select coalesce(sum(coalesce(filed_amount,estimated_amount)),0) value from tax_settlements where company_id=$1 and tax_model='130' and year=$2 and quarter<$3`,[i.companyId,year,quarter]),
    ]);
    const salesBase=n(sales.rows[0]?.base),salesTax=n(sales.rows[0]?.tax),purchaseBase=n(purchases.rows[0]?.base),purchaseTax=n(purchases.rows[0]?.tax),vatBalance=salesTax-purchaseTax,income=n(accSales.rows[0]?.value),expenses=n(accPurchases.rows[0]?.value),net=Math.max(0,income-expenses),applicable=profile.incomeTaxRegime==="direct",previousPayments=n(previous.rows[0]?.value),irpf=Math.max(0,net*n(profile.irpfRate)/100-previousPayments-n(profile.annualMinoration));
    return {year,quarter,from:bounds.from,to:bounds.to,label:`${quarter}T ${year}`,estimateLabel:"Estimación de FactuPapa",incomplete:Number(sales.rows[0]?.count??0)===0||Number(purchases.rows[0]?.count??0)===0,vat:{salesBase,salesTax,purchaseBase,deductibleTax:purchaseTax,balance:vatBalance},irpf:{applicable,regime:profile.incomeTaxRegime,accumulatedIncome:income,accumulatedExpenses:expenses,net,rate:n(profile.irpfRate),previousPayments,withholdings:0,result:irpf},reserve:Math.max(0,vatBalance)+(applicable?irpf:0),quality:{salesCount:Number(sales.rows[0]?.count??0),purchaseCount:Number(purchases.rows[0]?.count??0),warnings:[...(Number(sales.rows[0]?.count??0)===0?["No hay ventas contabilizadas en el periodo"]:[]),...(Number(purchases.rows[0]?.count??0)===0?["No hay compras confirmadas en el periodo"]:[])]}};
  }
}
